/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author El Gato
 */
public class ViewFrame extends javax.swing.JFrame{


    /**
     * Creates new form ViewFrame
     */
    public ViewFrame() {
        this.setIconImage(new javax.swing.ImageIcon("src/Model/Resources/tlogo.png").getImage());
        initComponents();
        game1.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Parent = new javax.swing.JPanel();
        cPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        Start = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        Instructions = new javax.swing.JButton();
        highScore = new javax.swing.JButton();
        Credits = new javax.swing.JButton();
        menuBG = new javax.swing.JLabel();
        instructionsPanel = new javax.swing.JPanel();
        instructions1 = new View.Panels.Instructions();
        creditsPanel = new javax.swing.JPanel();
        credits1 = new View.Panels.Credits();
        highscoresPanel = new javax.swing.JPanel();
        highScores1 = new View.Panels.ScoreBoard();
        gamePanel = new javax.swing.JPanel();
        try {
            game1 = new View.Panels.Game();
        } catch (java.io.FileNotFoundException e1) {
            e1.printStackTrace();
        }
        jPanel1 = new javax.swing.JPanel();
        headerNav = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(520, 650));
        setMinimumSize(new java.awt.Dimension(520, 650));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(520, 650));
        setResizable(false);

        Parent.setBackground(new java.awt.Color(0, 0, 153));
        Parent.setMaximumSize(new java.awt.Dimension(520, 650));
        Parent.setMinimumSize(new java.awt.Dimension(520, 650));
        Parent.setPreferredSize(new java.awt.Dimension(520, 650));

        cPanel.setMaximumSize(new java.awt.Dimension(520, 550));
        cPanel.setMinimumSize(new java.awt.Dimension(520, 550));
        cPanel.setPreferredSize(new java.awt.Dimension(520, 550));
        cPanel.setLayout(new java.awt.CardLayout());

        menuPanel.setMaximumSize(new java.awt.Dimension(520, 550));
        menuPanel.setMinimumSize(new java.awt.Dimension(520, 550));
        menuPanel.setPreferredSize(new java.awt.Dimension(520, 550));
        menuPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                menuPanelMouseMoved(evt);
            }
        });
        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Start.setBackground(new java.awt.Color(0, 0, 0));
        Start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Model/Resources/Start.png"))); // NOI18N
        Start.setBorder(null);
        Start.setBorderPainted(false);
        Start.setContentAreaFilled(false);
        Start.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Start.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Model/Resources/StartRO.png"))); // NOI18N
        Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartActionPerformed(evt);
            }
        });
        menuPanel.add(Start, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 500, 90));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Model/Resources/Exit.png"))); // NOI18N
        Exit.setBorderPainted(false);
        Exit.setContentAreaFilled(false);
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Model/Resources/ExitRO.png"))); // NOI18N
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        menuPanel.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 500, 90));

        Instructions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Model/Resources/Instructions.png"))); // NOI18N
        Instructions.setBorderPainted(false);
        Instructions.setContentAreaFilled(false);
        Instructions.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Instructions.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Model/Resources/InstructionsRO.png"))); // NOI18N
        Instructions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstructionsActionPerformed(evt);
            }
        });
        menuPanel.add(Instructions, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 490, 90));

        highScore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Model/Resources/HighScore.png"))); // NOI18N
        highScore.setBorderPainted(false);
        highScore.setContentAreaFilled(false);
        highScore.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        highScore.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Model/Resources/HighScoreRO.png"))); // NOI18N
        highScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highScoreActionPerformed(evt);
            }
        });
        menuPanel.add(highScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 500, 110));

        Credits.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Model/Resources/Credits.png"))); // NOI18N
        Credits.setBorderPainted(false);
        Credits.setContentAreaFilled(false);
        Credits.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Credits.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Model/Resources/CreditsRo.png"))); // NOI18N
        Credits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreditsActionPerformed(evt);
            }
        });
        menuPanel.add(Credits, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 500, 110));

        menuBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Model/Resources/yeah_boy.jpg"))); // NOI18N
        menuPanel.add(menuBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, -1));

        cPanel.add(menuPanel, "card2");

        javax.swing.GroupLayout instructionsPanelLayout = new javax.swing.GroupLayout(instructionsPanel);
        instructionsPanel.setLayout(instructionsPanelLayout);
        instructionsPanelLayout.setHorizontalGroup(
            instructionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(instructions1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        instructionsPanelLayout.setVerticalGroup(
            instructionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(instructions1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        cPanel.add(instructionsPanel, "card4");

        javax.swing.GroupLayout creditsPanelLayout = new javax.swing.GroupLayout(creditsPanel);
        creditsPanel.setLayout(creditsPanelLayout);
        creditsPanelLayout.setHorizontalGroup(
            creditsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(credits1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        creditsPanelLayout.setVerticalGroup(
            creditsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(credits1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        cPanel.add(creditsPanel, "card5");

        javax.swing.GroupLayout highscoresPanelLayout = new javax.swing.GroupLayout(highscoresPanel);
        highscoresPanel.setLayout(highscoresPanelLayout);
        highscoresPanelLayout.setHorizontalGroup(
            highscoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(highScores1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        highscoresPanelLayout.setVerticalGroup(
            highscoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(highScores1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        cPanel.add(highscoresPanel, "card6");

        gamePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        gamePanel.add(game1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        cPanel.add(gamePanel, "card6");

        javax.swing.GroupLayout ParentLayout = new javax.swing.GroupLayout(Parent);
        Parent.setLayout(ParentLayout);
        ParentLayout.setHorizontalGroup(
            ParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        ParentLayout.setVerticalGroup(
            ParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));

        headerNav.setForeground(new java.awt.Color(0, 51, 204));
        headerNav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Model/Resources/header.png"))); // NOI18N
        headerNav.setBorderPainted(false);
        headerNav.setContentAreaFilled(false);
        headerNav.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Model/Resources/headerRO.png"))); // NOI18N
        headerNav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                headerNavActionPerformed(evt);
            }
        });
        jPanel1.add(headerNav);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Parent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Parent, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed
        try {
            game1.initialize();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ViewFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        game1.setVisible(true);
        game1.invokeStart();
        
        cPanel.removeAll();
        cPanel.repaint();
        cPanel.revalidate();

        cPanel.add(gamePanel);
        cPanel.repaint();
        cPanel.revalidate();
    }//GEN-LAST:event_StartActionPerformed

    private void InstructionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstructionsActionPerformed
        cPanel.removeAll();
        cPanel.repaint();
        cPanel.revalidate();

        cPanel.add(instructionsPanel);
        cPanel.repaint();
        cPanel.revalidate();
    }//GEN-LAST:event_InstructionsActionPerformed

    private void highScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highScoreActionPerformed
        cPanel.removeAll();
        cPanel.repaint();
        cPanel.revalidate();

        cPanel.add(highscoresPanel);
        cPanel.repaint();
        cPanel.revalidate();
    }//GEN-LAST:event_highScoreActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void menuPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPanelMouseMoved

    }//GEN-LAST:event_menuPanelMouseMoved

    private void CreditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreditsActionPerformed
        cPanel.removeAll();
        cPanel.repaint();
        cPanel.revalidate();

        cPanel.add(creditsPanel);
        cPanel.repaint();
        cPanel.revalidate();
    }//GEN-LAST:event_CreditsActionPerformed

    private void headerNavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_headerNavActionPerformed
        if(game1.isVisible()){
            int reply = JOptionPane.showConfirmDialog(null,
                    "Quit?", 
                    null, 
                    JOptionPane.YES_NO_OPTION);
            if(reply == JOptionPane.YES_OPTION){
                cPanel.removeAll();
                cPanel.repaint();
                cPanel.revalidate();

                cPanel.add(menuPanel);
                cPanel.repaint();
                cPanel.revalidate();
                game1.resetTimer();
                game1.stopThreads();
                game1.setVisible(false);
            }
            else{}
        }
        else{
            cPanel.removeAll();
            cPanel.repaint();
            cPanel.revalidate();

            cPanel.add(menuPanel);
            cPanel.repaint();
            cPanel.revalidate();
        }
    }//GEN-LAST:event_headerNavActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Credits;
    private javax.swing.JButton Exit;
    private javax.swing.JButton Instructions;
    private javax.swing.JPanel Parent;
    private javax.swing.JButton Start;
    private javax.swing.JPanel cPanel;
    private View.Panels.Credits credits1;
    private javax.swing.JPanel creditsPanel;
    private View.Panels.Game game1;
    private javax.swing.JPanel gamePanel;
    private javax.swing.JButton headerNav;
    private javax.swing.JButton highScore;
    private View.Panels.ScoreBoard highScores1;
    private javax.swing.JPanel highscoresPanel;
    private View.Panels.Instructions instructions1;
    private javax.swing.JPanel instructionsPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel menuBG;
    private javax.swing.JPanel menuPanel;
    // End of variables declaration//GEN-END:variables

}
