/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Panels;

/**
 *
 * @author El Gato
 */
public class Instructions extends javax.swing.JPanel {

    /**
     * Creates new form Instructions
     */
    public Instructions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InstructionPanel = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        howTo = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        InstructionPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Model/Resources/logo.png"))); // NOI18N
        InstructionPanel.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, -1));

        howTo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Model/Resources/howTo.png"))); // NOI18N
        InstructionPanel.add(howTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 30, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Model/Resources/yeah_boy.jpg"))); // NOI18N
        Background.setToolTipText("");
        InstructionPanel.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InstructionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InstructionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JPanel InstructionPanel;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel howTo;
    // End of variables declaration//GEN-END:variables
}
