/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.Panels;

import View.Panels.*;
import java.io.FileNotFoundException;
import java.util.logging.Logger;

/**
 *
 * @author El Gato
 */
public class Menu extends javax.swing.JPanel {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        Start = new javax.swing.JButton();
        Instructions = new javax.swing.JButton();
        highScore = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        menuBG = new javax.swing.JLabel();

        menuPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                menuPanelMouseMoved(evt);
            }
        });
        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Start.setBackground(new java.awt.Color(0, 0, 0));
        Start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Model/Resources/Start.png"))); // NOI18N
        Start.setBorder(null);
        Start.setBorderPainted(false);
        Start.setContentAreaFilled(false);
        Start.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Start.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Model/Resources/StartRO.png"))); // NOI18N
        Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartActionPerformed(evt);
            }
        });
        menuPanel.add(Start, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 520, 90));

        Instructions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Model/Resources/Instructions.png"))); // NOI18N
        Instructions.setBorderPainted(false);
        Instructions.setContentAreaFilled(false);
        Instructions.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Instructions.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Model/Resources/InstructionsRO.png"))); // NOI18N
        Instructions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstructionsActionPerformed(evt);
            }
        });
        menuPanel.add(Instructions, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 520, 90));

        highScore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Model/Resources/HighScore.png"))); // NOI18N
        highScore.setBorderPainted(false);
        highScore.setContentAreaFilled(false);
        highScore.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        highScore.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Model/Resources/HighScoreRO.png"))); // NOI18N
        highScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highScoreActionPerformed(evt);
            }
        });
        menuPanel.add(highScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 520, 110));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Model/Resources/Exit.png"))); // NOI18N
        Exit.setBorderPainted(false);
        Exit.setContentAreaFilled(false);
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Model/Resources/ExitRO.png"))); // NOI18N
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        menuPanel.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 520, 90));

        menuBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Model/Resources/yeah_boy.jpg"))); // NOI18N
        menuPanel.add(menuBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed
//        InGame bogglePro = null;
//        try {
//            bogglePro = new InGame(this);
//        } catch (FileNotFoundException ex) {
//            Logger.getLogger(InGameMenu.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        bogglePro.setVisible(true);
        this.removeAll();
        this.revalidate();
        try{
            this.menuPanel.add(new Game());
        } catch (FileNotFoundException ex){
            System.out.println(ex);
        }
        this.repaint();
        //this.setVisible(false);
    }//GEN-LAST:event_StartActionPerformed

    private void InstructionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstructionsActionPerformed
//        new InstructionsUI().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_InstructionsActionPerformed

    private void highScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highScoreActionPerformed
//        try {
//            new HighScores(this).setVisible(true);
//        } catch (FileNotFoundException ex) {
//            Logger.getLogger(InGameMenu.class.getName()).log(Level.SEVERE, null, ex);
//        }
        this.setVisible(false);
    }//GEN-LAST:event_highScoreActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void menuPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPanelMouseMoved

    }//GEN-LAST:event_menuPanelMouseMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JButton Instructions;
    private javax.swing.JButton Start;
    private javax.swing.JButton highScore;
    private javax.swing.JLabel menuBG;
    private javax.swing.JPanel menuPanel;
    // End of variables declaration//GEN-END:variables
}
